server:
  port: 8002

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.com.com.tang.entities
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml

spring:
  application:
    name: cloudservice-dept
  datasource:
    url: jdbc:mysql://localhost:3306/cloudservice2?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: 123
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

eureka:
  client: #客户端注册到eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #集群配置
    # 单机  defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: cloudservice-dept8002 #给入驻eureka的服务改别名 自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示IP地址

#追加关于这个模块微服务的信息描述
info:
  app.name: cloudservice
  company.name: www.xxx.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}