server:
  port: 9527

spring:
  application:
    name: cloudservice-zuul-gateway

eureka:
  client: #客户端注册到eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

#zuul路由映射规则
zuul:
  prefix: /tang   #同一网关
  #  ignored-services: cloudservice-dept  #忽略cloudservice-dept
  ignored-services: "*"  #忽略全部服务的真实名字
  routes:
    dept.serviceId: cloudservice-dept
    dept.path: /mydept/** #将cloudservice-dept服务名字取别虚拟名mydept

info:
  app.name: cloudservice
  company.name: www.xxx.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

